In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("fin_transactions.txt")

In [3]:
df.head()

,transaction_id,date,account_id,category,description,amount,currency,status
0,1,1/2/2025,CHK-001,rent,January rent payment,"$1,250.00",USD,cleared
1,2,1/3/2025,CHK-001,Groceries,Supermarket run,154.23,USD,cleared
2,3,1/3/2025,CC-100,Dining,Team lunch,($48.90),USD,cleared
3,4,1/4/2025,CHK-001,utilities,Electric bill,NaN,USD,pending
4,5,1/5/2025,CC-100,Travel,Taxi to client site,$32.10,USD,cleared

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  40 non-null     int64
 1   date            38 non-null     object
 2   account_id      39 non-null     object
 3   category        40 non-null     object
 4   description     40 non-null     object
 5   amount          38 non-null     object
 6   currency        40 non-null     object
 7   status          40 non-null     object
dtypes: int64(1), object(7)
memory usage: 2.6+ KB

In [5]:
df.isna().sum()

transaction_id    0
date              2
account_id        1
category          0
description       0
amount            2
currency          0
status            0
dtype: int64

In [6]:
df.drop_duplicates(inplace=True)

In [8]:
df.shape

(40, 8)

In [9]:
df["amount"] = (df["amount"]
        .astype(str)
        .str.replace(r"[\$,]", "", regex=True)
        .str.strip()
)
df["amount"] = pd.to_numeric(df["amount"], errors="coerce")

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  40 non-null     int64
 1   date            38 non-null     object
 2   account_id      39 non-null     object
 3   category        40 non-null     object
 4   description     40 non-null     object
 5   amount          37 non-null     float64
 6   currency        40 non-null     object
 7   status          40 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.6+ KB

In [11]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  40 non-null     int64
 1   date            37 non-null     datetime64[ns]
 2   account_id      39 non-null     object
 3   category        40 non-null     object
 4   description     40 non-null     object
 5   amount          37 non-null     float64
 6   currency        40 non-null     object
 7   status          40 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 2.6+ KB

In [13]:
df["category"] = df["category"].str.strip().str.lower()

In [15]:
df.head()

,transaction_id,date,account_id,category,description,amount,currency,status
0,1,2025-01-02,CHK-001,rent,January rent payment,1250.00,USD,cleared
1,2,2025-01-03,CHK-001,groceries,Supermarket run,154.23,USD,cleared
2,3,2025-01-03,CC-100,dining,Team lunch,NaN,USD,cleared
3,4,2025-01-04,CHK-001,utilities,Electric bill,NaN,USD,pending
4,5,2025-01-05,CC-100,travel,Taxi to client site,32.10,USD,cleared

In [16]:
df["amount"] = df["amount"].fillna(0)
df["missing_flag"] = df.isna().any(axis=1)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  40 non-null     int64
 1   date            37 non-null     datetime64[ns]
 2   account_id      39 non-null     object
 3   category        40 non-null     object
 4   description     40 non-null     object
 5   amount          40 non-null     float64
 6   currency        40 non-null     object
 7   status          40 non-null     object
 8   missing_flag    40 non-null     bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 2.7+ KB

In [18]:
df.describe()

       transaction_id                           date      amount
count       40.000000                             37    40.00000
mean        20.500000  2025-01-15 12:58:22.702702592   271.78175
min          1.000000            2025-01-02 00:00:00  -500.00000
25%         10.750000            2025-01-09 00:00:00    11.04250
50%         20.500000            2025-01-15 00:00:00    40.45000
75%         30.250000            2025-01-22 00:00:00   137.92500
max         40.000000            2025-01-30 00:00:00  4500.00000
std         11.690452                            NaN   771.69803

In [19]:
df.isna().sum()

transaction_id    0
date              3
account_id        1
category          0
description       0
amount            0
currency          0
status            0
missing_flag      0
dtype: int64